/* v4.3 descriptive analytics; backend enforces suppression. No private data stored. */
(() => {
 'use strict';
 window.CMEIntelligence=({q,esc,rpc,getSeason,getMyData,getUserId})=>{
  let run=0,offset=0,sourceOffset=0,savedRun=0;
  const empty=s=>`<p class="empty-state" role="status">${esc(s)}</p>`;
  const note='<p class="workspace-note">Datos aportados por la comunidad. Las tasas describen a quienes reportaron y no representan a todos los solicitantes. No prueban que una señal haya causado una entrevista.</p>';
  const link=p=>`<a class="program-link" href="#/program/${encodeURIComponent(p.id)}">${esc(p.name)}</a>`;
  function wave(p){
   const rows=p?.timeline||[];
   return `<p><strong>${esc(p?.activity||'Insufficient data')}</strong> · ${esc(p?.context||'')}</p>`+(rows.length?`<ul class="wave-timeline" aria-label="Períodos de invitaciones reportadas">${rows.map(b=>`<li><span>${esc(b.cycle)} · ${b.resolution==='week'?'Semana de':'Mes de'} ${esc(b.period)}</span><strong>${esc(b.reports)} reportes</strong><span class="wave-marker" aria-hidden="true"></span></li>`).join('')}</ul><p class="workspace-note">Primera observación visible: ${esc(p.first_period)} · Última: ${esc(p.latest_period)} · ${esc(p.qualifying_periods)} períodos que cumplen el umbral. No son las fechas inicial o final reales del programa.</p>`:empty('Datos insuficientes. Los períodos sin una muestra de al menos 3 personas no se muestran; no equivalen a ausencia de invitaciones.'));
  }
  function signals(p){
   const groups=['Gold','Silver','None','Signal'];
   return `<p class="workspace-note">${esc(p?.signal_state||'Selecciona un ciclo específico.')}</p><div class="signal-grid">${groups.map(k=>{const g=p?.signals?.find(x=>x.signal===k),ok=g?.state==='available';return `<div class="signal-card"><h4>${k==='None'?'Sin signal':k==='Signal'?'Signal sin tipo':k}</h4>${ok?`<strong>${esc(g.rate)}%</strong><p>${esc(g.interviews)} entrevistas / ${esc(g.applications)} aplicaciones · n=${esc(g.applications)}</p><p>${g.applications<10?'Datos comunitarios limitados':g.applications<30?'Muestra comunitaria moderada':'Más datos comunitarios disponibles'}</p>`:empty('Datos insuficientes')} </div>`;}).join('')}</div>${note}`;
  }
  const sections=p=>`<article class="panel"><h3>Interview Waves</h3><button class="btn ghost small" data-ai-open="research" data-ai-ids="${esc(p?.id||'')}" data-ai-question="Explica las oleadas de entrevistas documentadas para este programa.">Explicar actividad</button>${wave(p)}</article><article class="panel"><h3>Signal Intelligence</h3><button class="btn ghost small" data-ai-open="research" data-ai-ids="${esc(p?.id||'')}" data-ai-question="Explica los resultados documentados por tipo de signal.">Explicar signals</button>${signals(p)}<p class="workspace-note">Aplicaciones de usuarios deduplicadas por persona/programa/ciclo. Mínimo 5 personas por signal, con protección de resultados pequeños. No se mezclan signals entre ciclos.</p><a href="#/data" class="btn ghost">Contribuir · actualizar mi actividad</a></article>`;
  const rateKeys={Gold:'Interview Rate — Gold Signal',Silver:'Interview Rate — Silver Signal',None:'Interview Rate — No Signal'};
  const rateValue=v=>typeof v==='number' && Number.isFinite(v) && v>=0 && v<=1?v:null;
  const rateText=v=>v==null?'Dato no disponible':(v*100).toFixed(1)+'%';
  function rateRecord(rows){return rows.find(r=>r.kind==='interview_rates'||Object.values(rateKeys).some(k=>Object.prototype.hasOwnProperty.call(r.fields||{},k)));}
  function rates(rows){const r=rateRecord(rows);return Object.fromEntries(Object.entries(rateKeys).map(([k,field])=>[k,rateValue(r?.fields?.[field])]));}
  function safeWeb(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)&&u.hostname.includes('.')&&!u.username&&!u.password&&!u.hostname.endsWith('.local')?u.href:null;}catch{return null;}}
  function website(rows){const r=rows.find(x=>safeWeb(x.website_url));return r?`<a class="btn ghost" href="${esc(safeWeb(r.website_url))}" target="_blank" rel="noopener noreferrer">${r.website_scope==='institution'?'Web de la institución':'Web del programa'} ↗</a><span class="workspace-note">Enlace revisado: ${esc(r.website_verified_at||'Fecha no documentada')}${r.website_scope==='institution'?' · Página específica de la residencia no verificada.':''}</span>`:'';}
  function strategy(rows){
   const r=rates(rows),items=[];
   const difference=(a,b)=>{if(r[a]!=null&&r[b]!=null){const d=Math.round((r[a]-r[b])*1000)/10;items.push(`${a==='None'?'Sin signal':a} frente a ${b==='None'?'sin signal':b}: ${d>0?'+':''}${d.toFixed(1)} puntos porcentuales.`);}};
   difference('Gold','None');difference('Silver','None');difference('Gold','Silver');
   return `<div class="signal-strategy"><h4>Estrategia de signals · lectura de los datos</h4>${items.length?`<ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p>Usa estas diferencias para valorar dónde expresar tu interés, junto con los requisitos del programa, tus preferencias y las señales que tengas disponibles. Una diferencia observada no demuestra el efecto de enviar una señal.</p>`:empty('No hay suficientes tasas documentadas para comparar tipos de signal en este programa.')}<p class="workspace-note">Las tasas describen grupos de solicitantes; no son tu probabilidad personal de entrevista. No se dispone de denominadores para calcular incertidumbre ni de una política de asignación de signals confirmada por el programa.</p></div>`;
  }
  function programSignals(rows){const r=rateRecord(rows);if(!r)return '';const v=rates(rows);return `<section class="program-signal-summary" aria-label="Entrevistas por signal"><h3>Tasas de entrevista por signal</h3><p class="workspace-note">Datos del programa${r.source_cycle?' · ciclo '+esc(r.source_cycle):''}. Este período es independiente del selector de actividad comunitaria.</p><div class="signal-grid program-signal-grid">${['Gold','Silver','None'].map(k=>`<div class="signal-card"><h4>${k==='None'?'Sin signal':k}</h4><strong>${esc(rateText(v[k]))}</strong><p>Entrevistas entre quienes aplicaron con esta opción.</p></div>`).join('')}</div>${strategy(rows)}</section>`;}
  const fieldLabels={'Interview Rate (Average Likelihood)':'Tasa de entrevista general','Interview Rate — Silver Signal':'Tasa de entrevista · Silver','Interview Rate — Gold Signal':'Tasa de entrevista · Gold','Interview Rate — No Signal':'Tasa de entrevista · sin signal','Interview Rate — In-State School':'Tasa de entrevista · escuela en el estado','Interview Rate — Out-of-State School':'Tasa de entrevista · escuela fuera del estado','Interview Rate — MD':'Tasa de entrevista · MD','Interview Rate — DO':'Tasa de entrevista · DO','Interview Rate — US IMG':'Tasa de entrevista · US IMG','Interview Rate — Non-US IMG':'Tasa de entrevista · Non-US IMG','Step 2 CK All Invited — Middle 80%':'Step 2 CK de invitados · rango central 80%','Level 2 CE DOs Invited — Middle 80%':'Level 2 CE de invitados DO · rango central 80%'};
  function fieldValue(k,v){if(/Interview Rate|^Tendencia de aplicaciones/.test(k))return esc(rateText(rateValue(v)));if(v==null||['!','Unavailable','Not Available','N/A',''].includes(String(v).trim()))return 'Dato no disponible';const url=safeWeb(v);return url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Abrir enlace del programa ↗</a>`:esc(v);}
  function resources(rows){return rows.length?`<article class="panel program-guide-details"><h3>Información del programa</h3><div class="program-website">${website(rows)}</div>${programSignals(rows)}${rows.map(s=>`<details><summary>${s.kind==='interview_rates'||rateRecord([s])?'Todas las tasas y características de los invitados':'Requisitos, contacto y características del programa'} · ${s.source_cycle?'ciclo '+esc(s.source_cycle):esc(s.source_date||'Fecha no documentada')}</summary><dl class="workspace-details">${Object.entries(s.fields||{}).map(([k,v])=>`<div><dt>${esc(fieldLabels[k]||k)}</dt><dd>${fieldValue(k,v)}</dd></div>`).join('')}</dl></details>`).join('')}<p class="workspace-note">Confirma los requisitos vigentes en la web institucional antes de aplicar. Las tendencias de aplicaciones describen una muestra de referencia de tamaño no documentado; no representan a todos los solicitantes ni son tasas de entrevista. Los valores no disponibles no equivalen a cero.</p></article>`:'';}
  const compareRows=[...['Gold','Silver','None'].map(k=>[`${k==='None'?'Sin signal':k} · tasa del programa`,p=>{const r=rateRecord(p.resources||[]);return `${esc(rateText(rates(p.resources||[])[k]))}${r?.source_cycle?' · ciclo '+esc(r.source_cycle):''}`;}]),['Estrategia de signals',p=>strategy(p.resources||[])],['Actividad reciente · comunidad',p=>esc(p.v43?.activity||'Insufficient data')],['Oleadas reportadas',p=>wave(p.v43)],...['Gold','Silver','None'].map(k=>[`${k==='None'?'Sin signal':k} · tasa comunitaria`,p=>{const g=p.v43?.signals?.find(x=>x.signal===k);return g?.state==='available'?`${esc(g.rate)}% · ${esc(g.interviews)}/${esc(g.applications)} · n=${esc(g.applications)}`:'Datos insuficientes';}]),['Contexto de la muestra comunitaria',p=>esc(p.v43?.context||'')],['Información del programa',p=>resources(p.resources||[])]];
  function cycle(){const v=q('waveCycle').value;return v==='all'?null:Number(v);}
  async function load(){
   const n=++run;q('waveResults').innerHTML=empty('Cargando observaciones protegidas…');
   try{const d=await rpc('specialty_wave_overview_v43',{p_specialty:q('waveSpecialty').value||null,p_cycle:cycle(),p_state:q('waveState').value.trim().toUpperCase()||null,p_query:q('waveProgram').value.trim(),p_offset:offset});if(n!==run)return;
    q('waveResults').innerHTML=(d.programs||[]).map(p=>`<article class="panel"><h3>${link(p)}</h3><p>${esc(p.specialty)} · ${esc(p.state||'Estado no documentado')}</p>${getSeason().tools(p)}${wave(p)}<details><summary>Signal Intelligence</summary>${signals(p)}</details></article>`).join('')||empty('No se encontraron programas. Amplía los filtros.');
    q('wavePager').innerHTML=`<button class="btn ghost" data-wave-page="-1" ${offset===0?'disabled':''}>Anterior</button><span>Página ${offset/30+1}</span><button class="btn ghost" data-wave-page="1" ${!d.has_more?'disabled':''}>Siguiente</button>`;
   }catch(e){if(n===run)q('waveResults').innerHTML=empty('No se pudieron cargar los datos. Reintenta cuando tengas conexión.')+'<button class="btn ghost" data-wave-retry>Reintentar</button>';}
  }
  let sourceRun=0;
  async function loadSources(){
   const n=++sourceRun;q('sourceResults').innerHTML=empty('Cargando programas…');q('sourcePager').innerHTML='';
   try{const d=await rpc('program_source_directory_v43',{p_query:q('sourceSearch').value.trim(),p_offset:sourceOffset});if(n!==sourceRun)return;
    q('sourceResults').innerHTML=(d.programs||[]).map(s=>`<article class="panel program-guide-card"><h3>${s.program_id?link({id:s.program_id,name:s.name}):esc(s.name)}</h3><p>${esc([s.city,s.state].filter(Boolean).join(', '))} · ACGME: ${esc(s.acgme_program_id||'Identidad sin resolver')}</p>${s.program_id?`<a class="btn ghost" href="#/program/${encodeURIComponent(s.program_id)}">Ver perfil y comparar</a>`:''}${resources(s.resources||[s])}</article>`).join('')||empty('No se encontraron programas.');
    q('sourcePager').innerHTML=`<button class="btn ghost" data-source-page="-1" ${sourceOffset===0?'disabled':''}>Anterior</button><span>Página ${sourceOffset/30+1}</span><button class="btn ghost" data-source-page="1" ${!d.has_more?'disabled':''}>Siguiente</button>`;
   }catch{if(n===sourceRun)q('sourceResults').innerHTML=empty('No se pudo cargar la guía de programas.')+'<button class="btn ghost" data-source-retry>Reintentar</button>';}
  }
  async function saved(){
   const n=++savedRun,uid=getUserId(),hosts=[q('matchIntelligence'),q('watchlistIntelligence')];
   const intro='<article class="panel"><h2>Match Season Intelligence</h2><p>Actividad comunitaria de tus programas guardados; no estima tus probabilidades.</p><a class="btn primary" href="#/waves">Interview Wave Tracker</a>';
   if(!uid){hosts.forEach(h=>{if(h)h.innerHTML=intro+'</article>';});return;}
   const ids=getSeason().getSaved().map(s=>s.program_id),selected=q('personalCycle')?.value,c=getMyData().cycles.find(x=>x.id===selected)||getMyData().cycles[0];
   if(!ids.length){hosts.forEach(h=>{if(h)h.innerHTML=intro+'<p>Guarda programas para ver su actividad agregada aquí.</p></article>';});return;}
   try{const batches=[];for(let i=0;i<ids.length;i+=50)batches.push(rpc('program_season_intelligence_v43',{p_ids:ids.slice(i,i+50),p_cycle:Number(c?.cycle)||null}));const rows=(await Promise.all(batches)).flat();if(n!==savedRun||uid!==getUserId())return;const recent=rows.filter(p=>['Active now','Recent activity'].includes(p.activity)),signal=rows.filter(p=>p.signals.some(g=>g.state==='available'));const html=intro+`<p>${recent.length} guardados con actividad reciente visible · ${signal.length} con tasas de signal disponibles para el ciclo seleccionado.</p>`+recent.slice(0,8).map(p=>`<p>${link(p)} · ${esc(p.activity)} · ${esc(p.latest_period)}</p>`).join('')+'<p class="workspace-note">Cero programas visibles no implica cero invitaciones. Las muestras pequeñas se suprimen.</p></article>';hosts.forEach(h=>{if(h)h.innerHTML=html;});}catch{hosts.forEach(h=>{if(h)h.innerHTML=intro+empty('No se pudieron cargar las observaciones de tus programas guardados.')+'</article>';});}
  }
  document.addEventListener('submit',e=>{if(e.target.id==='waveFilters'){e.preventDefault();offset=0;load();}if(e.target.id==='sourceFilters'){e.preventDefault();sourceOffset=0;loadSources();}});
  document.addEventListener('click',e=>{const w=e.target.closest('[data-wave-page]'),s=e.target.closest('[data-source-page]');if(w){offset=Math.max(0,offset+Number(w.dataset.wavePage)*30);load();}if(s){sourceOffset=Math.max(0,sourceOffset+Number(s.dataset.sourcePage)*30);loadSources();}if(e.target.closest('[data-wave-retry]'))load();if(e.target.closest('[data-source-retry]'))loadSources();});
  return {load,loadSources,saved,wave,signals,sections,resources,compareRows,website,programSignals,strategy};
 };
})();
