/* v4.3 descriptive analytics; backend enforces suppression. No private data stored. */
(() => {
 'use strict';
 window.CMEIntelligence=({q,esc,rpc,getSeason,getMyData,getUserId})=>{
  let run=0,offset=0,sourceOffset=0,savedRun=0;
  const empty=s=>`<p class="empty-state" role="status">${esc(s)}</p>`;
  const note='<p class="workspace-note">Datos aportados por la comunidad. Las tasas describen a quienes reportaron y no representan a todos los solicitantes. No prueban que una señal haya causado una entrevista.</p>';
  const link=p=>`<a class="program-link" href="#/program/${encodeURIComponent(p.id)}">${esc(p.name)}</a>`;
  function wave(p){
   const rows=p?.timeline||[];
   return `<p><strong>${esc(p?.activity||'Insufficient data')}</strong> · ${esc(p?.context||'')}</p>`+(rows.length?`<ul class="wave-timeline" aria-label="Períodos de invitaciones reportadas">${rows.map(b=>`<li><span>${esc(b.cycle)} · ${b.resolution==='week'?'Semana de':'Mes de'} ${esc(b.period)}</span><strong>${esc(b.reports)} reportes</strong><span class="wave-marker" aria-hidden="true"></span></li>`).join('')}</ul><p class="workspace-note">Primera observación visible: ${esc(p.first_period)} · Última: ${esc(p.latest_period)} · ${esc(p.qualifying_periods)} períodos que cumplen el umbral. No son las fechas inicial o final reales del programa.</p>`:empty('Datos insuficientes. Los períodos sin una muestra de al menos 3 personas no se muestran; no equivalen a ausencia de invitaciones.'));
  }
  function signals(p){
   const groups=['Gold','Silver','None','Signal'];
   return `<p class="workspace-note">${esc(p?.signal_state||'Selecciona un ciclo específico.')}</p><div class="signal-grid">${groups.map(k=>{const g=p?.signals?.find(x=>x.signal===k),ok=g?.state==='available';return `<div class="signal-card"><h4>${k==='None'?'Sin signal':k==='Signal'?'Signal sin tipo':k}</h4>${ok?`<strong>${esc(g.rate)}%</strong><p>${esc(g.interviews)} entrevistas / ${esc(g.applications)} aplicaciones · n=${esc(g.applications)}</p><p>${g.applications<10?'Datos comunitarios limitados':g.applications<30?'Muestra comunitaria moderada':'Más datos comunitarios disponibles'}</p>`:empty('Datos insuficientes')} </div>`;}).join('')}</div>${note}`;
  }
  const sections=p=>`<article class="panel"><h3>Interview Waves</h3>${wave(p)}</article><article class="panel"><h3>Signal Intelligence</h3>${signals(p)}<p class="workspace-note">Aplicaciones de usuarios deduplicadas por persona/programa/ciclo. Mínimo 5 personas por signal, con protección de resultados pequeños. No se mezclan signals entre ciclos.</p><a href="#/data" class="btn ghost">Contribuir · actualizar mi actividad</a></article>`;
  function resources(rows){return rows.length?`<article class="panel"><h3>Información externa del programa</h3><p class="workspace-note">Fuentes aportadas por el propietario. Se muestran por separado de la comunidad; las tasas externas pueden tener otros denominadores. No se importaron scores, compatibilidad ni probabilidades personales del solicitante.</p>${rows.map(s=>`<details><summary>${esc(s.source)} · ${s.source_cycle?'ciclo '+esc(s.source_cycle):'criterios del programa'} · ${esc(s.source_date||'Fecha de consulta no documentada')}</summary><p><a href="${esc(s.program_url)}" target="_blank" rel="noopener noreferrer">${esc(s.source)} · abrir fuente ↗</a></p><dl class="workspace-details">${Object.entries(s.fields||{}).map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${typeof v==='string' && /^https:\/\//.test(v)?`<a href="${esc(v)}" target="_blank" rel="noopener noreferrer">Abrir web del programa ↗</a>`:esc(typeof v==='number' && /Rate/.test(k)?(v*100).toFixed(1)+'%':v)}</dd></div>`).join('')}</dl></details>`).join('')}</article>`:'';}
  const compareRows=[['Actividad reciente · comunidad',p=>esc(p.v43?.activity||'Insufficient data')],['Oleadas reportadas',p=>wave(p.v43)],...['Gold','Silver','None'].map(k=>[`${k==='None'?'Sin signal':k} · tasa observada`,p=>{const g=p.v43?.signals?.find(x=>x.signal===k);return g?.state==='available'?`${esc(g.rate)}% · ${esc(g.interviews)}/${esc(g.applications)} · n=${esc(g.applications)}`:'Datos insuficientes';}]),['Contexto de la muestra',p=>esc(p.v43?.context||'')],['Fuentes externas del programa',p=>resources(p.resources||[])]];
  function cycle(){const v=q('waveCycle').value;return v==='all'?null:Number(v);}
  async function load(){
   const n=++run;q('waveResults').innerHTML=empty('Cargando observaciones protegidas…');
   try{const d=await rpc('specialty_wave_overview_v43',{p_specialty:q('waveSpecialty').value||null,p_cycle:cycle(),p_state:q('waveState').value.trim().toUpperCase()||null,p_query:q('waveProgram').value.trim(),p_offset:offset});if(n!==run)return;
    q('waveResults').innerHTML=(d.programs||[]).map(p=>`<article class="panel"><h3>${link(p)}</h3><p>${esc(p.specialty)} · ${esc(p.state||'Estado no documentado')}</p>${getSeason().tools(p)}${wave(p)}<details><summary>Signal Intelligence</summary>${signals(p)}</details></article>`).join('')||empty('No se encontraron programas. Amplía los filtros.');
    q('wavePager').innerHTML=`<button class="btn ghost" data-wave-page="-1" ${offset===0?'disabled':''}>Anterior</button><span>Página ${offset/30+1}</span><button class="btn ghost" data-wave-page="1" ${!d.has_more?'disabled':''}>Siguiente</button>`;
   }catch(e){if(n===run)q('waveResults').innerHTML=empty('No se pudieron cargar los datos. Reintenta cuando tengas conexión.')+'<button class="btn ghost" data-wave-retry>Reintentar</button>';}
  }
  async function loadSources(){q('sourceResults').innerHTML=empty('Cargando fuentes de programas…');try{const d=await rpc('program_source_directory_v43',{p_query:q('sourceSearch').value.trim(),p_offset:sourceOffset});q('sourceResults').innerHTML=(d.programs||[]).map(s=>`<article class="panel"><h3>${s.program_id?link({id:s.program_id,name:s.name}):esc(s.name)}</h3><p>${esc([s.city,s.state].filter(Boolean).join(', '))} · ACGME: ${esc(s.acgme_program_id||'Identidad sin resolver')}</p>${!s.program_id?'<p class="workspace-warning">No se atribuyen métricas comunitarias a esta entrada sin identidad oficial resuelta.</p>':''}${resources([s])}</article>`).join('')||empty('No se encontraron programas.');q('sourcePager').innerHTML=`<button class="btn ghost" data-source-page="-1" ${sourceOffset===0?'disabled':''}>Anterior</button><span>Página ${sourceOffset/30+1}</span><button class="btn ghost" data-source-page="1" ${!d.has_more?'disabled':''}>Siguiente</button>`;}catch{q('sourceResults').innerHTML=empty('No se pudo cargar el catálogo de fuentes.');}}
  async function saved(){
   const n=++savedRun,uid=getUserId(),hosts=[q('matchIntelligence'),q('watchlistIntelligence')];
   const intro='<article class="panel"><h2>Match Season Intelligence</h2><p>Actividad comunitaria de tus programas guardados; no estima tus probabilidades.</p><a class="btn primary" href="#/waves">Interview Wave Tracker</a>';
   if(!uid){hosts.forEach(h=>{if(h)h.innerHTML=intro+'</article>';});return;}
   const ids=getSeason().getSaved().map(s=>s.program_id),selected=q('personalCycle')?.value,c=getMyData().cycles.find(x=>x.id===selected)||getMyData().cycles[0];
   if(!ids.length){hosts.forEach(h=>{if(h)h.innerHTML=intro+'<p>Guarda programas para ver su actividad agregada aquí.</p></article>';});return;}
   try{const batches=[];for(let i=0;i<ids.length;i+=50)batches.push(rpc('program_season_intelligence_v43',{p_ids:ids.slice(i,i+50),p_cycle:Number(c?.cycle)||null}));const rows=(await Promise.all(batches)).flat();if(n!==savedRun||uid!==getUserId())return;const recent=rows.filter(p=>['Active now','Recent activity'].includes(p.activity)),signal=rows.filter(p=>p.signals.some(g=>g.state==='available'));const html=intro+`<p>${recent.length} guardados con actividad reciente visible · ${signal.length} con tasas de signal disponibles para el ciclo seleccionado.</p>`+recent.slice(0,8).map(p=>`<p>${link(p)} · ${esc(p.activity)} · ${esc(p.latest_period)}</p>`).join('')+'<p class="workspace-note">Cero programas visibles no implica cero invitaciones. Las muestras pequeñas se suprimen.</p></article>';hosts.forEach(h=>{if(h)h.innerHTML=html;});}catch{hosts.forEach(h=>{if(h)h.innerHTML=intro+empty('No se pudieron cargar las observaciones de tus programas guardados.')+'</article>';});}
  }
  document.addEventListener('submit',e=>{if(e.target.id==='waveFilters'){e.preventDefault();offset=0;load();}if(e.target.id==='sourceFilters'){e.preventDefault();sourceOffset=0;loadSources();}});
  document.addEventListener('click',e=>{const w=e.target.closest('[data-wave-page]'),s=e.target.closest('[data-source-page]');if(w){offset=Math.max(0,offset+Number(w.dataset.wavePage)*30);load();}if(s){sourceOffset=Math.max(0,sourceOffset+Number(s.dataset.sourcePage)*30);loadSources();}if(e.target.closest('[data-wave-retry]'))load();});
  return {load,loadSources,saved,wave,signals,sections,resources,compareRows};
 };
})();
