const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict'),path=require('path');
(async()=>{const dom=new JSDOM(fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),{url:'https://cubamatchexplorer.org',runScripts:'outside-only'}),w=dom.window;
const calls=[],row={acgme_program_id:'1400321025',name:'Program <script>bad()</script>',specialty:'Internal Medicine',state:'AZ',acgme_status:'Accredited',eras_status:'Mixed participation',eras_season:2027,acgme_url:'javascript:alert(1)',eras_url:'https://systems.aamc.org/eras/erasstats/par/display.cfm?SPEC_CD=140',eras_tracks:[{name:'Preliminary',status:'Not Participating'},{name:'Categorical',status:'Participating'}]};
const rpc=async(name,args)=>{calls.push({name,args});if(name==='program_catalog_health')return {sources:[{source:'acgme',specialties_total:190,specialties_synced:100,specialties_fresh:100,specialties_failed:1,programs:1000,errors:[{specialty:'Example',error:'HTTP 503'}]}]};if(name==='program_catalog_watch')return {programs:[row],has_more:true,total:90};return [];};
w.eval(fs.readFileSync(path.join(__dirname,'../notifications.js'),'utf8'));const n=w.CMENotifications({q:id=>w.document.getElementById(id),esc:s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),api:async()=>[],rpc,getUserId:()=>'',isAdmin:()=>false,toast:()=>{},getSeason:()=>({tools:()=>''})});
await n.radar();const content=w.document.getElementById('radarContent');assert(content.textContent.includes('Preliminary'));assert(content.textContent.includes('Not Participating'));assert(!content.querySelector('script'));assert(!content.querySelector('[href^="javascript"]'));assert(w.document.getElementById('catalogHealth').textContent.includes('incidencias'));
w.document.querySelector('[data-radar-page="1"]').click();await new Promise(r=>setTimeout(r,15));assert.equal(calls.filter(x=>x.name==='program_catalog_watch').at(-1).args.p_offset,30);
const form=w.document.getElementById('radarFilter');form.elements.state.value='fl';form.elements.query.value='140';form.elements.status.value='Unregistered';form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,15));const last=calls.filter(x=>x.name==='program_catalog_watch').at(-1).args;assert.equal(last.p_offset,0);assert.equal(last.p_state,'FL');assert.equal(last.p_status,'Unregistered');assert.equal(last.p_query,'140');
console.log('PASS Radar catalogue filters, paging, track-specific statuses, partial-source warning and safe links');dom.window.close();})();
