const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('assert');
(async()=>{const dom=new JSDOM(fs.readFileSync('v43/index.html','utf8'),{url:'https://cuba-match-explorer.vercel.app/',runScripts:'outside-only'});const w=dom.window;let uid='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',rows=[{id:'one',title:'<script>bad</script>',body:'Safe notice',notification_type:'new_program',created_at:new Date().toISOString(),action_path:'https://evil.invalid',read_at:null}],p=[],r=[],saved=[];
const api=async(path,o={})=>{if(path.includes('/notifications')){if(o.method==='PATCH'){rows.forEach(x=>x.read_at=o.body.read_at);return null;}return rows;}
 if(path.includes('notification_preferences')){if(o.method==='POST'){p=[o.body];return null;}return p;}
 if(path.includes('radar_subscriptions')){if(o.method==='POST'){r=[o.body];return null;}return r;}return [];};
const rpc=async(name,args,publicOnly)=>{if(name.startsWith('notification_'))assert.strictEqual(publicOnly,false,'private RPC must use authenticated mode');return name==='notification_unread_count'?rows.filter(x=>!x.read_at).length:name==='notification_channel_status'?{push_ready:false,email_ready:false}:[];};
w.eval(fs.readFileSync('v43/notifications.js','utf8'));const n=w.CMENotifications({q:id=>w.document.getElementById(id),esc:s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),api,rpc,getUserId:()=>uid,isAdmin:()=>false,toast:()=>{},getSeason:()=>({tools:()=>''})});await n.load();assert.equal(w.document.getElementById('notificationUnread').textContent,'1');assert(!w.document.querySelector('#notificationCenter script'));assert.equal(w.document.querySelector('#notificationCenter a.btn.primary').getAttribute('href'),'#/notification-center');
w.document.querySelector('[data-notif-read]').click();await new Promise(r=>setTimeout(r,20));assert(w.document.getElementById('notificationUnread').hidden);
const f=w.document.getElementById('notificationPrefsForm');f.elements.timezone.value='America/New_York';f.elements.email.checked=true;f.elements.quiet_start.value='22:00';f.elements.quiet_end.value='07:00';f.elements.digest.value='daily';f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,20));assert.equal(p[0].email,true);assert.equal(p[0].digest,'daily');assert.equal(p[0].quiet_end,'07:00');
const rf=w.document.getElementById('radarPrefsForm');rf.elements.enabled.checked=true;rf.elements.specialties.value='Internal Medicine\nFamily Medicine';rf.elements.states.value='FL, NY';rf.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,20));assert.equal(r[0].states.join(','),'FL,NY');
await n.radar();assert(w.document.getElementById('radarContent').textContent.includes('No hay nuevos'));uid='';await n.load();assert(w.document.getElementById('notificationCenter').textContent.includes('Inicia sesión'));assert(!w.document.getElementById('notificationCenter').textContent.includes('Safe notice'));
console.log('PASS notification badge/read, escaped content, safe route, preferences/quiet/digest, Radar filters, signout clearing');dom.window.close();})();
