const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const d=new JSDOM('<form id="presenceFilters"></form><div id="presenceResults"></div><div id="presenceAnalytics"></div><div id="presencePager"></div>',{url:'https://example.test/#/presence?evidence=documented&school=elam',runScripts:'outside-only'}),w=d.window,q=id=>w.document.getElementById(id),calls=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
w.eval(fs.readFileSync('presence.js','utf8'));
const rpc=async(name,args)=>{calls.push([name,args]);return name==='presence_directory_v53'?{programs:[{id:'x',name:'<img src=x onerror=alert(1)>',specialty:'Family medicine',presence:{status:'documented',total_count:1,current_count:1,historical_count:0}}],total:1,has_more:false}:{totals:{programs:1,current:1,historical:0,people:1,latino:0},coverage:{catalog:7469,reviewed:10,complete_reviews:0},states:[],schools:[],specialties:[],top_programs:[],school_options:[{id:'elam',name:'ELAM'}]};};
const m=w.CMEPresence({q,esc,rpc,getSeason:()=>({tools:()=>''}),getWorkspace:()=>({tray:()=>{}})});
(async()=>{await m.load();assert.equal(calls[0][1].p_filters.school,'elam');assert.equal(q('presenceFilters').elements.school.value,'elam');assert.equal(w.document.querySelectorAll('img').length,0);assert.match(q('presenceResults').textContent,/1 programas encontrados/);
const html=m.sections({presence:{status:'unknown'},people:[{full_name:'<script>unsafe</script>',school_name:'ELAM',effective_status:'historical',role:'alumnus',education_status:'graduated',linkedin_url:'https://linkedin.com.evil.test/in/fake',education_source:{url:'javascript:alert(1)',name:'Bad source'},source:{url:'https://real.test',name:'Good source'}}]});q('presenceResults').innerHTML=html;assert.equal(w.document.querySelectorAll('script').length,0);assert.equal(w.document.querySelectorAll('[href^="javascript:"]').length,0);assert(!html.includes('href="https://linkedin.com.evil.test'));assert.match(q('presenceResults').textContent,/Histórico/);assert.match(q('presenceResults').textContent,/no identificado públicamente/);assert.equal(m.safeUrl('https://user:password@host.test'),null);
assert.match(m.badge({status:'unknown'}),/Revisión pendiente/);assert(!m.badge({status:'unknown'}).includes('0 personas'));console.log('Presence DOM: school deep link, combined filters, escaping, sources, uncertain evidence passed');w.close();})().catch(e=>{console.error(e);process.exitCode=1;w.close();});
