const test=require('node:test'),assert=require('node:assert/strict');
const {validate,sql}=require('../scripts/presence-import.cjs');
// Synthetic importer fixtures, never imported into production.
const source={name:'QA institution',url:'https://example.org/education',type:'institutional',note:'Synthetic fixture',verified_at:'2026-10-05'};
const sample={version:'5.3',verified_at:'2026-10-05',scope:'synthetic test',schools:[{id:'elam',name:'ELAM',aliases:[]}],people:[{id:'qa-professional',full_name:'Synthetic QA professional',school_id:'elam',education_status:'medical_education',education_source:source,verified_at:'2026-10-05',confidence:'high'}],affiliations:[{id:'qa-history',person_id:'qa-professional',acgme_program_id:'0000000000',temporal_status:'historical',role:'alumnus',period_key:'test',source,verified_at:'2026-10-05',published:false}],reviews:[],aggregates:[]};
const copy=()=>structuredClone(sample);
test('school evidence independently includes ELAM residents and preserves professional history',()=>{validate(sample);assert(sample.people.some(p=>p.school_id==='elam'));assert(sample.affiliations.some(a=>a.temporal_status==='historical'));assert.equal(new Set(sample.people.map(p=>p.id)).size,1);const result=sql(sample);assert.match(result,/Program identity requires manual resolution/);assert.doesNotMatch(result,/delete from/i);assert.match(result,/excluded.verified_at>=presence_people.verified_at/);});
test('refuses sensitive extra fields and missing evidence',()=>{for(const field of ['nationality','ethnicity','email','phone']){const d=copy();d.people[0][field]='test';assert.throws(()=>validate(d),/Unsupported/);}const d=copy();delete d.people[0].education_source;assert.throws(()=>validate(d),/Education evidence/);});
test('refuses duplicate people, fake LinkedIn host and source credential URLs',()=>{let d=copy();d.people.push(d.people[0]);assert.throws(()=>validate(d),/Duplicate/);d=copy();d.people[0].linkedin_url='https://linkedin.com.evil.test/in/person';assert.throws(()=>validate(d),/LinkedIn/);d=copy();d.people[0].education_source.url='https://user:pass@school.test';assert.throws(()=>validate(d),/HTTPS/);});
