import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const PROJECT_URL=Deno.env.get('SUPABASE_URL')!;
const SECRET_KEYS=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');
const SECRET_KEY=SECRET_KEYS['default'];
const SEARCH_URL='https://apps.acgme.org/ads/Public/Programs/Search';
const ORIGIN='https://apps.acgme.org';
const UA='CubaMatchExplorer/1.0 (+https://xqjjiveuvnioachgxqez.supabase.co/functions/v1/cuba-match-explorer)';

function decode(s:string){return s.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&#x27;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#x2F;/gi,'/').replace(/\s+/g,' ').trim()}
function strip(s:string){return decode(s.replace(/<br\s*\/?\s*>/gi,' ').replace(/<[^>]+>/g,' '))}
function norm(s:string){return strip(s).toLowerCase().replace(/[–—]/g,'-').replace(/\s+/g,' ').trim()}
function abs(href:string){try{return new URL(href,ORIGIN).toString()}catch{return SEARCH_URL}}
function getToken(html:string){return html.match(/name=["']__RequestVerificationToken["'][^>]*value=["']([^"']+)/i)?.[1]||''}
function getCookies(headers:Headers){const h:any=headers;const a=typeof h.getSetCookie==='function'?h.getSetCookie():[];return a.map((x:string)=>x.split(';')[0]).join('; ')}
async function db(path:string,init:RequestInit={}){if(!SECRET_KEY)throw new Error('Supabase secret key unavailable');const r=await fetch(PROJECT_URL+'/rest/v1/'+path,{...init,headers:{apikey:SECRET_KEY,'Content-Type':'application/json',...(init.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(`DB ${r.status}: ${t.slice(0,700)}`);return t?JSON.parse(t):null}
async function upsert(table:string,rows:any[],conflict:string){for(let i=0;i<rows.length;i+=100){await db(`${table}?on_conflict=${encodeURIComponent(conflict)}`,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows.slice(i,i+100))})}}
function parseSpecialties(html:string){const block=html.match(/<select\b[^>]*id=["']specialtyFilter["'][^>]*>[\s\S]*?<\/select>/i)?.[0]||'';const out:any[]=[];for(const m of block.matchAll(/<option\b([^>]*)>([\s\S]*?)<\/option>/gi)){const attrs=m[1],id=attrs.match(/value=["']?([^"' >]*)/i)?.[1]||'',name=strip(m[2]);if(/^\d+$/.test(id)&&name&&/class=["'][^"']*optionGroup/i.test(attrs))out.push({acgme_specialty_id:id,name,active:true})}return out}
function parsePrograms(html:string,fallback:string){const out:any[]=[];for(const m of html.matchAll(/<tr\b([^>]*)>([\s\S]*?)<\/tr>/gi)){const attrs=m[1],row=m[2],cells=[...row.matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>strip(x[1]));const idx=cells.findIndex(c=>/^\d{10}$/.test(c.replace(/\D/g,'')));if(idx<0)continue;const code=cells[idx].replace(/\D/g,''),specialty=cells[idx+1]||fallback,name=cells[idx+2]||'',city=cells[idx+3]||null;if(!name)continue;const internalId=attrs.match(/data-item-key=["']([^"']+)/i)?.[1]||null;const detail=row.match(/href=["']([^"']*\/ads\/Public\/Programs\/Detail\?orgCode=[^"']+)["']/i)?.[1]||`/ads/Public/Programs/Detail?orgCode=${code}`;const hist=row.match(/href=["']([^"']*AccreditationHistoryReport\?programId=[^"']+)["']/i)?.[1]||null;out.push({acgme_program_id:code,name,specialty,city,state:null,institution:null,source:'ACGME Public',active:true,_internalId:internalId,_detail:abs(detail),_history:hist?abs(hist):null})}return out}
async function session(){const r=await fetch(SEARCH_URL,{headers:{'User-Agent':UA,Accept:'text/html,application/xhtml+xml'}});if(!r.ok)throw new Error(`ACGME GET ${r.status}`);const html=await r.text(),token=getToken(html),cookie=getCookies(r.headers);if(!token)throw new Error('ACGME verification token not found');return{html,token,cookie,specialties:parseSpecialties(html)}}
async function fetchSpecialty(s:any,sess:any){const p=new URLSearchParams();p.set('__RequestVerificationToken',sess.token);p.set('accreditationTypeId','2');p.set('specialtyId',s.acgme_specialty_id);p.set('specialtyCategoryTypeId','');p.set('stateId','');p.set('numCode','');p.set('city','');p.set('g-recaptcha-response','');const r=await fetch(SEARCH_URL,{method:'POST',headers:{'User-Agent':UA,Accept:'text/html,application/xhtml+xml','Content-Type':'application/x-www-form-urlencoded','Cookie':sess.cookie,'Referer':SEARCH_URL},body:p.toString()});if(!r.ok)throw new Error(`ACGME POST ${r.status}`);const rows=parsePrograms(await r.text(),s.name);if(!rows.length)throw new Error('No program rows returned');return rows}
async function enrich(p:any){try{const r=await fetch(p._detail,{headers:{'User-Agent':UA,Accept:'text/html'}});if(!r.ok)return{};const text=strip(await r.text());const z=text.match(/\b([A-Z]{2})\s+\d{5}(?:-\d{4})?\b/);const status=text.match(/Accreditation Status\s*[:\-]?\s*([^|]{2,90}?)(?:Effective|Program Director|Address|$)/i)?.[1]?.trim()||null;const dr=text.match(/(?:Accreditation )?Effective Date\s*[:\-]?\s*(\d{1,2}\/\d{1,2}\/\d{4}|\d{4}-\d{2}-\d{2})/i)?.[1]||null;let effective_date=null;if(dr){const d=new Date(dr);if(!isNaN(d.getTime()))effective_date=d.toISOString().slice(0,10)}return{state:z?.[1]||null,accreditation_status:status,effective_date}}catch{return{}}}

Deno.serve(async(req:Request)=>{const u=new URL(req.url);if(u.pathname.endsWith('/health'))return Response.json({ok:true,service:'ACGME incremental monitor',version:4});let body:any={};try{body=await req.json()}catch{}
 try{
  const watchedPrograms=await db('rpc/notification_monitor_targets',{method:'POST',body:'{}'})||[];
  for(const p of watchedPrograms){try{const e=await enrich({_detail:p.source_url});if(e.accreditation_status)await db('rpc/notification_record_program_status',{method:'POST',body:JSON.stringify({p_id:p.id,p_status:e.accreditation_status,p_date:e.effective_date||null})});}catch{}}
  const sess=await session();if(!sess.specialties.length)throw new Error('No ACGME specialties discovered');
  await upsert('acgme_specialties',sess.specialties,'acgme_specialty_id');
  const states=await db('acgme_specialties?select=acgme_specialty_id,name,baseline_complete,last_synced_at,last_program_count,last_error&active=eq.true')||[];
  const watches=await db('program_watch_subscriptions?select=specialty&enabled=eq.true')||[];const watched=new Set(watches.map((x:any)=>norm(x.specialty)));
  const stateById=new Map(states.map((x:any)=>[x.acgme_specialty_id,x]));
  const enriched=sess.specialties.map((s:any)=>({...s,...(stateById.get(s.acgme_specialty_id)||{})}));
  const manual=body?.specialty_id?enriched.filter((x:any)=>x.acgme_specialty_id===String(body.specialty_id)):[];
  const watchedRows=enriched.filter((x:any)=>watched.has(norm(x.name))).sort((a:any,b:any)=>new Date(a.last_synced_at||0).getTime()-new Date(b.last_synced_at||0).getTime());
  const oldest=enriched.slice().sort((a:any,b:any)=>{const ai=norm(a.name)==='internal medicine'&&!a.baseline_complete?-1:0,bi=norm(b.name)==='internal medicine'&&!b.baseline_complete?-1:0;if(ai!==bi)return ai-bi;return new Date(a.last_synced_at||0).getTime()-new Date(b.last_synced_at||0).getTime()});
  const targets:any[]=[];const add=(x:any)=>{if(x&&!targets.some(t=>t.acgme_specialty_id===x.acgme_specialty_id))targets.push(x)};manual.forEach(add);watchedRows.slice(0,2).forEach(add);for(const x of oldest){if(targets.length>=4)break;add(x)}
  const started=await db('acgme_sync_runs',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({status:'running',details:{mode:'incremental',target_specialties:targets.map(x=>x.name)}})});const runId=started?.[0]?.id;
  let seen=0,newCount=0;const errors:any[]=[];
  for(const s of targets){try{
    const existingRows=await db(`programs?select=acgme_program_id&specialty=eq.${encodeURIComponent(s.name)}`)||[];const existing=new Set(existingRows.map((x:any)=>x.acgme_program_id));const baseline=!s.baseline_complete&&existing.size===0;
    const programs=await fetchSpecialty(s,sess);seen+=programs.length;
    await upsert('programs',programs.map(({_internalId,_detail,_history,...p})=>p),'acgme_program_id');
    const acgmeSources=programs.map((p:any)=>({acgme_program_id:p.acgme_program_id,source:'acgme',external_id:p._internalId||null,source_url:p._detail,data_scope:'ACGME official public program detail',last_verified_at:new Date().toISOString()}));
    const freidaSources=programs.map((p:any)=>({acgme_program_id:p.acgme_program_id,source:'freida',external_id:null,source_url:`https://freida.ama-assn.org/program/${p.acgme_program_id}`,data_scope:'AMA FREIDA interactive listing; external fields are not mirrored without licensing',last_verified_at:new Date().toISOString()}));
    const reSources=programs.map((p:any)=>({acgme_program_id:p.acgme_program_id,source:'residency_explorer',external_id:null,source_url:'https://www.residencyexplorer.org/',data_scope:'Official interactive tool; no bulk dataset mirroring',last_verified_at:new Date().toISOString()}));
    await upsert('program_external_sources',acgmeSources,'source,acgme_program_id');await upsert('program_external_sources',freidaSources,'source,acgme_program_id');await upsert('program_external_sources',reSources,'source,acgme_program_id');
    if(!baseline){const newly=programs.filter((p:any)=>!existing.has(p.acgme_program_id));if(newly.length){const events:any[]=[];for(const p of newly.slice(0,100)){const e=await enrich(p);events.push({event_key:`acgme-first-seen:${p.acgme_program_id}`,acgme_program_id:p.acgme_program_id,program_name:p.name,specialty:p.specialty,city:p.city,state:e.state||null,accreditation_status:e.accreditation_status||'Newly detected in ACGME public directory',effective_date:e.effective_date||null,source_url:p._detail,last_seen_at:new Date().toISOString()})}await upsert('accreditation_events',events,'event_key');newCount+=events.length}}
    await db(`acgme_specialties?acgme_specialty_id=eq.${encodeURIComponent(s.acgme_specialty_id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({baseline_complete:true,last_synced_at:new Date().toISOString(),last_program_count:programs.length,last_error:null})});
   }catch(e){const msg=String((e as Error)?.message||e);errors.push({specialty:s.name,error:msg});await db(`acgme_specialties?acgme_specialty_id=eq.${encodeURIComponent(s.acgme_specialty_id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_synced_at:new Date().toISOString(),last_error:msg})})}}
  if(runId)await db(`acgme_sync_runs?id=eq.${runId}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:errors.length===targets.length?'failed':'completed',completed_at:new Date().toISOString(),programs_seen:seen,new_programs:newCount,error_message:errors.length===targets.length?'All specialties failed':null,details:{mode:'incremental',targets:targets.map(x=>x.name),errors}})});
  return Response.json({ok:errors.length<targets.length,targets:targets.map(x=>x.name),programs_seen:seen,new_programs:newCount,errors});
 }catch(e){return Response.json({ok:false,error:String((e as Error)?.message||e)},{status:500})}
});
