-- Cuba Match Explorer v3.4 — Admin: delete a user account completely
-- Safe to run more than once. Run AFTER 004_repair_rpcs_and_admin.sql.
--
-- admin_delete_user(p_user_id) removes the account from auth.users. Every
-- table that belongs to a user references auth.users ON DELETE CASCADE, so in
-- one transaction this deletes:
--   profiles, applicant_cycles, program_reports (and their moderation_audit
--   rows), program_watch_subscriptions, notifications, plus Supabase's own
--   auth.identities / auth.sessions / refresh tokens.
-- Community aggregates are computed live, so they update immediately.

-- 1) moderation_audit blocked the deletion of anyone who had ever moderated a
--    report (ON DELETE RESTRICT). Keep the audit trail of other users'
--    reports but drop the link to the deleted moderator.
alter table public.moderation_audit alter column moderator_user_id drop not null;
alter table public.moderation_audit drop constraint if exists moderation_audit_moderator_user_id_fkey;
alter table public.moderation_audit
  add constraint moderation_audit_moderator_user_id_fkey
  foreign key (moderator_user_id) references auth.users(id) on delete set null;

-- 2) Minimal, non-personal log of deletions (who deleted, when, how many rows).
--    It stores NO id, email or content of the deleted user.
create table if not exists public.admin_deletion_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid references auth.users(id) on delete set null,
  deleted_cycles integer not null default 0,
  deleted_reports integer not null default 0,
  deleted_alerts integer not null default 0,
  deleted_notifications integer not null default 0,
  created_at timestamptz not null default now()
);
alter table public.admin_deletion_log enable row level security;
drop policy if exists admin_deletion_log_read on public.admin_deletion_log;
create policy admin_deletion_log_read on public.admin_deletion_log
  for select to authenticated using (public.is_admin());
revoke all on public.admin_deletion_log from anon;
grant select on public.admin_deletion_log to authenticated;

-- 3) The deletion function. Only role = 'admin' (not moderators) may use it.
create or replace function public.admin_delete_user(p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_role text;
  v_admins integer;
  v_cycles integer;
  v_reports integer;
  v_alerts integer;
  v_notifs integer;
begin
  if not exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') then
    raise exception 'Admin required';
  end if;
  if p_user_id is null then raise exception 'User id required'; end if;
  if p_user_id = auth.uid() then
    raise exception 'An administrator cannot delete their own account from the admin panel';
  end if;

  select role into v_role from public.profiles where id = p_user_id;
  if v_role is null and not exists (select 1 from auth.users where id = p_user_id) then
    raise exception 'User not found';
  end if;
  if v_role = 'admin' then
    select count(*) into v_admins from public.profiles where role = 'admin';
    if v_admins <= 1 then raise exception 'Cannot delete the last administrator'; end if;
  end if;

  select count(*) into v_cycles  from public.applicant_cycles where user_id = p_user_id;
  select count(*) into v_reports from public.program_reports where user_id = p_user_id;
  select count(*) into v_alerts  from public.program_watch_subscriptions where user_id = p_user_id;
  select count(*) into v_notifs  from public.notifications where user_id = p_user_id;

  -- Explicit deletes first (belt and braces), then the auth account itself,
  -- which cascades to everything else.
  delete from public.program_reports where user_id = p_user_id;
  delete from public.applicant_cycles where user_id = p_user_id;
  delete from public.program_watch_subscriptions where user_id = p_user_id;
  delete from public.notifications where user_id = p_user_id;
  delete from public.profiles where id = p_user_id;
  delete from auth.users where id = p_user_id;

  insert into public.admin_deletion_log(admin_user_id, deleted_cycles, deleted_reports, deleted_alerts, deleted_notifications)
  values (auth.uid(), v_cycles, v_reports, v_alerts, v_notifs);

  return jsonb_build_object(
    'cycles', v_cycles, 'reports', v_reports,
    'alerts', v_alerts, 'notifications', v_notifs);
end;
$$;

revoke all on function public.admin_delete_user(uuid) from public, anon;
grant execute on function public.admin_delete_user(uuid) to authenticated;

notify pgrst, 'reload schema';
